# Generated by Django 2.0.7 on 2018-07-30 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 17, 39, 1, 42971, tzinfo=utc), verbose_name='date published'),
        ),
    ]
