# Generated by Django 2.0.7 on 2018-07-31 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180730_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 16, 51, 44, 371148, tzinfo=utc)),
        ),
    ]
